// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfG9evQuDCLS_9R7TIicpahi-O1Hnjl4',
    appId: '1:836828274707:web:065087efa076d2cde51fe6',
    messagingSenderId: '836828274707',
    projectId: 'quiz-app-6b1c9',
    authDomain: 'quiz-app-6b1c9.firebaseapp.com',
    storageBucket: 'quiz-app-6b1c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyMc77DTan3AWjwidrhR1FNND1BkBko8',
    appId: '1:836828274707:android:9276b0398ff03d52e51fe6',
    messagingSenderId: '836828274707',
    projectId: 'quiz-app-6b1c9',
    storageBucket: 'quiz-app-6b1c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_RVFUanV_nQYk3H-C8fHcNH-iX8edouY',
    appId: '1:836828274707:ios:e4300b04f6fd36f9e51fe6',
    messagingSenderId: '836828274707',
    projectId: 'quiz-app-6b1c9',
    storageBucket: 'quiz-app-6b1c9.appspot.com',
    iosClientId: '836828274707-qi532kkqn0otmkpjh7sltf41976oa1hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.formValidation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_RVFUanV_nQYk3H-C8fHcNH-iX8edouY',
    appId: '1:836828274707:ios:e4300b04f6fd36f9e51fe6',
    messagingSenderId: '836828274707',
    projectId: 'quiz-app-6b1c9',
    storageBucket: 'quiz-app-6b1c9.appspot.com',
    iosClientId: '836828274707-qi532kkqn0otmkpjh7sltf41976oa1hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.formValidation',
  );
}
